[package]
name = "crudapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.mongodb]
version = "2.3.0"
features = ["tokio-sync"]

[dependencies]
hex = "0.4.3"