[package]
name = "testdriver"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.29.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.mongodb]
version = "2.6.0"
features = ["aws-auth"]
# default-features = false

